from contextlib import asynccontextmanager
import os
from pathlib import Path
from typing import Annotated, Any, Iterator

from dotenv import load_dotenv
from fastapi import Depends, FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import AliasChoices, BaseModel, Field
from psycopg import Connection, connect
from psycopg.rows import dict_row


load_dotenv(Path(__file__).resolve().parent.parent / ".env")
DATABASE_URL = os.environ.get("DATABASE_URL")


class ProductInput(BaseModel):
    name: str = Field(min_length=1, max_length=120)
    category: str = Field(min_length=1, max_length=80)
    price: float = Field(ge=0)
    stock: int = Field(ge=0)


class Product(ProductInput):
    id: int


class CustomerInput(BaseModel):
    first_name: str = Field(
        min_length=1,
        max_length=80,
        validation_alias=AliasChoices("first_name", "firstName"),
        serialization_alias="firstName",
    )
    last_name: str = Field(
        min_length=1,
        max_length=80,
        validation_alias=AliasChoices("last_name", "lastName"),
        serialization_alias="lastName",
    )
    position: str | None = Field(default=None, max_length=120)
    mobile: str | None = Field(default=None, max_length=40)


class Customer(CustomerInput):
    id: int


class OrderLineInput(BaseModel):
    product_id: int = Field(gt=0)
    quantity: int = Field(gt=0)


class OrderInput(BaseModel):
    customer_id: int = Field(gt=0)
    lines: list[OrderLineInput] = Field(min_length=1)


class OrderLine(OrderLineInput):
    product: Product


class Order(BaseModel):
    id: int
    customer: Customer
    lines: list[OrderLine]


def get_connection() -> Iterator[Connection[dict[str, Any]]]:
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL must be set to a PostgreSQL connection string.")
    with connect(DATABASE_URL, row_factory=dict_row) as connection:
        yield connection


Database = Annotated[Connection[dict[str, Any]], Depends(get_connection)]


def initialize_database() -> None:
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL must be set to start the API.")
    with connect(DATABASE_URL, row_factory=dict_row) as connection:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS products (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                category TEXT NOT NULL,
                price DOUBLE PRECISION NOT NULL CHECK (price >= 0),
                stock INTEGER NOT NULL CHECK (stock >= 0)
            );
            CREATE TABLE IF NOT EXISTS customers (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                first_name TEXT NOT NULL,
                last_name TEXT NOT NULL,
                position TEXT,
                mobile TEXT
            );
            CREATE TABLE IF NOT EXISTS orders (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE RESTRICT
            );
            CREATE TABLE IF NOT EXISTS order_lines (
                order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
                product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
                quantity INTEGER NOT NULL CHECK (quantity > 0),
                PRIMARY KEY (order_id, product_id)
            );
            """
        )
        if connection.execute("SELECT COUNT(*) FROM products").fetchone()[0] == 0:
            connection.executemany(
                "INSERT INTO products (name, category, price, stock) VALUES (%s, %s, %s, %s)",
                [
                    ("Cap", "Hats", 828, 25),
                    ("2 Color T-Shirt", "Hats", 144, 43),
                    ("Polo Tshirt", "Men's cloths", 28, 123),
                    ("Couple Set", "Men's cloths", 85, 33),
                    ("Collection", "Collection", 113, 11),
                    ("Balt Bag", "Collection", 28, 123),
                    ("Female Polo T-Shirt", "Women's cloths", 92, 323),
                    ("Half Pant", "Women's cloths", 35, 52),
                    ("Bag", "Accessories", 13, 25),
                    ("Glasses", "Glases", 828, 30),
                ],
            )


@asynccontextmanager
async def lifespan(_: FastAPI):
    initialize_database()
    yield


app = FastAPI(title="Inventory Management API", version="1.0.0", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def product_from_row(row: dict[str, Any]) -> Product:
    return Product(**row)


def customer_from_row(row: dict[str, Any]) -> Customer:
    return Customer(**row)


def fetch_product(database: Connection[dict[str, Any]], product_id: int) -> Product:
    row = database.execute("SELECT * FROM products WHERE id = %s", (product_id,)).fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="Product not found")
    return product_from_row(row)


def fetch_customer(database: Connection[dict[str, Any]], customer_id: int) -> Customer:
    row = database.execute(
        "SELECT * FROM customers WHERE id = %s",
        (customer_id,),
    ).fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="Customer not found")
    return customer_from_row(row)


@app.get("/", tags=["root"])
def read_root() -> dict[str, str]:
    return {"message": "Inventory Management API is running."}


@app.get("/api/products", response_model=list[Product], tags=["products"])
def list_products(database: Database) -> list[Product]:
    return [product_from_row(row) for row in database.execute("SELECT * FROM products ORDER BY id")]


@app.post("/api/products", response_model=Product, status_code=status.HTTP_201_CREATED, tags=["products"])
def create_product(product: ProductInput, database: Database) -> Product:
    cursor = database.execute(
        "INSERT INTO products (name, category, price, stock) VALUES (%s, %s, %s, %s) RETURNING id",
        (product.name, product.category, product.price, product.stock),
    ).fetchone()
    return fetch_product(database, cursor["id"])


@app.get("/api/products/{product_id}", response_model=Product, tags=["products"])
def get_product(product_id: int, database: Database) -> Product:
    return fetch_product(database, product_id)


@app.put("/api/products/{product_id}", response_model=Product, tags=["products"])
def update_product(product_id: int, product: ProductInput, database: Database) -> Product:
    fetch_product(database, product_id)
    database.execute(
        "UPDATE products SET name = %s, category = %s, price = %s, stock = %s WHERE id = %s",
        (product.name, product.category, product.price, product.stock, product_id),
    )
    return fetch_product(database, product_id)


@app.delete("/api/products/{product_id}", status_code=status.HTTP_204_NO_CONTENT, tags=["products"])
def delete_product(product_id: int, database: Database) -> None:
    fetch_product(database, product_id)
    database.execute("DELETE FROM products WHERE id = %s", (product_id,))


@app.get("/api/customers", response_model=list[Customer], tags=["customers"])
def list_customers(database: Database) -> list[Customer]:
    rows = database.execute(
        "SELECT * FROM customers ORDER BY id"
    )
    return [customer_from_row(row) for row in rows]


@app.post("/api/customers", response_model=Customer, status_code=status.HTTP_201_CREATED, tags=["customers"])
def create_customer(customer: CustomerInput, database: Database) -> Customer:
    cursor = database.execute(
        "INSERT INTO customers (first_name, last_name, position, mobile) VALUES (%s, %s, %s, %s) RETURNING id",
        (customer.first_name, customer.last_name, customer.position, customer.mobile),
    ).fetchone()
    return fetch_customer(database, cursor["id"])


@app.get("/api/customers/{customer_id}", response_model=Customer, tags=["customers"])
def get_customer(customer_id: int, database: Database) -> Customer:
    return fetch_customer(database, customer_id)


@app.put("/api/customers/{customer_id}", response_model=Customer, tags=["customers"])
def update_customer(customer_id: int, customer: CustomerInput, database: Database) -> Customer:
    fetch_customer(database, customer_id)
    database.execute(
        "UPDATE customers SET first_name = %s, last_name = %s, position = %s, mobile = %s WHERE id = %s",
        (customer.first_name, customer.last_name, customer.position, customer.mobile, customer_id),
    )
    return fetch_customer(database, customer_id)


@app.delete("/api/customers/{customer_id}", status_code=status.HTTP_204_NO_CONTENT, tags=["customers"])
def delete_customer(customer_id: int, database: Database) -> None:
    fetch_customer(database, customer_id)
    database.execute("DELETE FROM customers WHERE id = %s", (customer_id,))


def fetch_order(database: Connection[dict[str, Any]], order_id: int) -> Order:
    row = database.execute("SELECT id, customer_id FROM orders WHERE id = %s", (order_id,)).fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="Order not found")
    line_rows = database.execute(
        """
        SELECT order_lines.product_id, order_lines.quantity, products.id, products.name,
               products.category, products.price, products.stock
        FROM order_lines JOIN products ON products.id = order_lines.product_id
        WHERE order_lines.order_id = %s
        """,
        (order_id,),
    )
    return Order(
        id=row["id"],
        customer=fetch_customer(database, row["customer_id"]),
        lines=[
            OrderLine(product_id=line["product_id"], quantity=line["quantity"], product=product_from_row(line))
            for line in line_rows
        ],
    )


@app.get("/api/orders", response_model=list[Order], tags=["orders"])
def list_orders(database: Database) -> list[Order]:
    return [fetch_order(database, row["id"]) for row in database.execute("SELECT id FROM orders ORDER BY id")]


@app.post("/api/orders", response_model=Order, status_code=status.HTTP_201_CREATED, tags=["orders"])
def create_order(order: OrderInput, database: Database) -> Order:
    fetch_customer(database, order.customer_id)
    for line in order.lines:
        fetch_product(database, line.product_id)
    cursor = database.execute("INSERT INTO orders (customer_id) VALUES (%s) RETURNING id", (order.customer_id,)).fetchone()
    database.executemany(
        "INSERT INTO order_lines (order_id, product_id, quantity) VALUES (%s, %s, %s)",
        [(cursor["id"], line.product_id, line.quantity) for line in order.lines],
    )
    return fetch_order(database, cursor["id"])


@app.get("/api/orders/{order_id}", response_model=Order, tags=["orders"])
def get_order(order_id: int, database: Database) -> Order:
    return fetch_order(database, order_id)


@app.put("/api/orders/{order_id}", response_model=Order, tags=["orders"])
def update_order(order_id: int, order: OrderInput, database: Database) -> Order:
    fetch_order(database, order_id)
    fetch_customer(database, order.customer_id)
    for line in order.lines:
        fetch_product(database, line.product_id)
    database.execute("UPDATE orders SET customer_id = %s WHERE id = %s", (order.customer_id, order_id))
    database.execute("DELETE FROM order_lines WHERE order_id = %s", (order_id,))
    database.executemany(
        "INSERT INTO order_lines (order_id, product_id, quantity) VALUES (%s, %s, %s)",
        [(order_id, line.product_id, line.quantity) for line in order.lines],
    )
    return fetch_order(database, order_id)


@app.delete("/api/orders/{order_id}", status_code=status.HTTP_204_NO_CONTENT, tags=["orders"])
def delete_order(order_id: int, database: Database) -> None:
    fetch_order(database, order_id)
    database.execute("DELETE FROM orders WHERE id = %s", (order_id,))